### ISSUE TITLE
首页流量统计显示优化

### ISSUE THREAD

**Issue by flyflas** [hamster1963/nezha-dash-react#7]
1. 流量统计各项之间没有间隔
2. 流量统计并没有并排显示（如图中2所示，右侧有大片的空白）
3. 如中3中所示，流量监控名称似乎有BUG，不能和右下角显示相同的名称。

![CleanShot 2024-11-30 at 21 07 50@2x](https://github.com/user-attachments/assets/e01f5847-315e-4f68-85df-be4d5ef265f8)

**Comment by hamster1963** [comment]
已移交到https://github.com/hamster1963/nezha-dash/issues/136
